"""phase 2 multi-tenant schema

Revision ID: 59cca7f5f05a
Revises: 
Create Date: 2026-05-18 22:32:33.934852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '59cca7f5f05a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('FACTORY', 'CARRIER', 'DISTRIBUTOR', name='company_kind'), nullable=False),
    sa.Column('carrier_type', sa.Enum('HYBRID', 'FORWARDER', 'ASSET_ONLY', name='carrier_type'), nullable=True),
    sa.Column('tax_id', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargo',
    sa.Column('factory_id', sa.Uuid(), nullable=False),
    sa.Column('distributor_id', sa.Uuid(), nullable=False),
    sa.Column('reference_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=False),
    sa.Column('volume_m3', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('required_body_type', sa.Enum('TENT', 'REFRIGERATOR', 'FLATBED', 'TANK', 'CONTAINER', 'OTHER', name='body_type'), nullable=True),
    sa.Column('origin_address', sa.String(length=512), nullable=False),
    sa.Column('origin_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('origin_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('destination_address', sa.String(length=512), nullable=False),
    sa.Column('destination_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('destination_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('pickup_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pickup_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'DISTRIBUTED', 'CARRIER_ACCEPTED', 'ASSIGNED_TRUCK', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'FAILED', name='cargo_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['factory_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_code')
    )
    op.create_table('trucks',
    sa.Column('carrier_id', sa.Uuid(), nullable=True),
    sa.Column('is_spot', sa.Boolean(), nullable=False),
    sa.Column('spot_source', sa.Enum('LORRY', 'TELEGRAM', 'MANUAL', name='spot_source'), nullable=True),
    sa.Column('spot_added_by_company_id', sa.Uuid(), nullable=True),
    sa.Column('plate_number', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('capacity_kg', sa.Integer(), nullable=False),
    sa.Column('capacity_volume_m3', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('body_type', sa.Enum('TENT', 'REFRIGERATOR', 'FLATBED', 'TANK', 'CONTAINER', 'OTHER', name='body_type'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BUSY', 'LOADING', 'UNLOADING', 'MAINTENANCE', 'OFF_DUTY', name='truck_status'), nullable=False),
    sa.Column('current_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('current_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('last_location_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_base_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('home_base_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['spot_added_by_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'DISPATCHER', 'ACCOUNTANT', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('cargo_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('TTN', 'DELIVERY_RECEIPT', 'DISCREPANCY_ACT', 'INVOICE', 'CONTRACT', name='document_kind'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ISSUED', 'PICKED_UP_SIGNED', 'DELIVERED_SIGNED', 'DISCREPANCY', 'CANCELLED', name='document_status'), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('factory_signature', sa.Text(), nullable=True),
    sa.Column('factory_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('factory_signed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('driver_pickup_signature', sa.Text(), nullable=True),
    sa.Column('driver_pickup_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('driver_delivery_signature', sa.Text(), nullable=True),
    sa.Column('driver_delivery_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distributor_signature', sa.Text(), nullable=True),
    sa.Column('distributor_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distributor_signed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('discrepancy_notes', sa.Text(), nullable=True),
    sa.Column('actual_weight_kg', sa.Integer(), nullable=True),
    sa.Column('actual_volume_m3', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('qr_code_payload', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('drivers',
    sa.Column('carrier_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.Column('current_truck_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_truck_id'], ['trucks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('truck_id', sa.Uuid(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_history', schema=None) as batch_op:
        batch_op.create_index('ix_location_history_truck_time', ['truck_id', 'recorded_at'], unique=False)

    op.create_table('assignments',
    sa.Column('cargo_id', sa.Uuid(), nullable=False),
    sa.Column('parent_assignment_id', sa.Uuid(), nullable=True),
    sa.Column('carrier_id', sa.Uuid(), nullable=False),
    sa.Column('truck_id', sa.Uuid(), nullable=True),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'ACCEPTED', 'FORWARDED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='assignment_status'), nullable=False),
    sa.Column('assigned_by', sa.Enum('SYSTEM', 'FACTORY', 'CARRIER', name='assignment_source'), nullable=False),
    sa.Column('planned_pickup_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_delivery_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('optimization_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['carrier_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index('ix_assignments_cargo', ['cargo_id'], unique=False)
        batch_op.create_index('ix_assignments_carrier', ['carrier_id'], unique=False)
        batch_op.create_index('ix_assignments_parent', ['parent_assignment_id'], unique=False)
        batch_op.create_index('ix_assignments_truck_status', ['truck_id', 'status'], unique=False)

    op.create_table('truck_schedule',
    sa.Column('truck_id', sa.Uuid(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.Enum('WORK', 'DAY_OFF', 'MAINTENANCE', 'ASSIGNMENT', name='schedule_kind'), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('truck_schedule', schema=None) as batch_op:
        batch_op.create_index('ix_truck_schedule_truck_window', ['truck_id', 'start_at', 'end_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck_schedule', schema=None) as batch_op:
        batch_op.drop_index('ix_truck_schedule_truck_window')

    op.drop_table('truck_schedule')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_assignments_truck_status')
        batch_op.drop_index('ix_assignments_parent')
        batch_op.drop_index('ix_assignments_carrier')
        batch_op.drop_index('ix_assignments_cargo')

    op.drop_table('assignments')
    with op.batch_alter_table('location_history', schema=None) as batch_op:
        batch_op.drop_index('ix_location_history_truck_time')

    op.drop_table('location_history')
    op.drop_table('drivers')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_table('trucks')
    op.drop_table('cargo')
    op.drop_table('companies')
    # ### end Alembic commands ###
